    server:
      port: 8080
    spring:
      application:
        name: newapp3
      datasource:
                url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5433/DEVFlow}
                username: ${JDBC_DATABASE_USERNAME:postgres}
                password: ${JDBC_DATABASE_PASSWORD:xxxxx}
                hikari:
                  connection-timeout: 30000
                  maximum-pool-size: 10
      jpa:
        hibernate:
          ddl-auto: update
        open-in-view: false
        properties:
          hibernate:
            jdbc:
              lob:
                non_contextual_creation: true
            id:
              new_generator_mappings: true
            types:
              print:
                banner: false
      servlet:
        multipart:
          max-file-size: 20MB
          max-request-size: 20MB
      security:
        oauth2:
          client:
            provider:
              keycloak:
                issuer-uri: ${ISSUER_URI:https://ngcloak.onrender.com/realms/softwareEngineer}

            registration:
              keycloak:
                provider: keycloak
                client_id: ${KEYCLOAK_CLIENT_ID:softwareEngineer}
                client_secret: ${KEYCLOAK_CLIENT_SECRET:rJuSSQDWuFvATo2pNlAlj0pTVJAbBNPo}
                authorization-grant-type: authorization_code
                scope: openid,profile,email
      thymeleaf:
        cache: false
